#
# Copyright (c) 2023 Volkswagen AG
# Copyright (c) 2023 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

# -- Number of replicas of the Kubernetes deployment
replicaCount: 1

image:
  # -- Repository of the docker image

  repository: tractusx/app-puris-backend
  # -- THe policy for the image pull process
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- List of used secrets
imagePullSecrets: []
# -- Possibility to override the name
nameOverride: ""
# -- Possibility to override the fullname
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations added to a running pod
podAnnotations: {}

# -- Added security contexts for a pod
podSecurityContext: {}
  # fsGroup: 2000

# Following Catena-X Helm Best Practices @url: https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01/
# @url: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
# -- Security configurations
securityContext:
  # -- Get more privileges than the parent process
  allowPrivilegeEscalation: false
  # -- Configures the non-root privileges for a run
  runAsNonRoot: true
  # -- Configures the user id for a run
  runAsUser: 1000
  # -- Configures the group id of a user for a run
  runAsGroup: 3000

service:
  # -- Type of the service
  type: NodePort
  # -- The port of the service
  port: 8081

# Following Catena-X Helm Best Practices @url: https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01/
# @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits
resources:
  # -- Maximum resource limits of CPU und memory
  limits:
    cpu: 2000m
    memory: 2048Mi
  # -- Minimum requested resources for CPU und memory
  requests:
    cpu: 1000m
    memory: 2048Mi

autoscaling:
  # -- Enable or disable the autoscaling of pods
  enabled: false

ingress:
  # -- Enable the Ingress
  enabled: false

  annotations:
    # -- Kubernetes Ingress class annotation for direct bindings
    kubernetes.io/ingress.class: nginx
    # -- Force redirects from HTTP to HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # -- Pass SSL traffic to the backend ports
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # -- The backend protocol type (e.g. HTTP)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  # -- Hosts for the Ingress controller
  hosts:
    - host: "puris-backend.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- TLS certificates for the Ingress controller
  tls:
    - secretName: tls-secret
      hosts:
        - puris-backend.net

# -- Constrains for the node selector
nodeSelector: {}

# -- Constrains for tolerations
tolerations: []

# Following Catena-X Helm Best Practices @url: https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01/
# @url: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity:
  podAntiAffinity:
    # -- Rules for the scheduler to find a pod
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            # -- Matching Expressions as key and operators for the pod affinity
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: DoesNotExist
          # -- Topology key of the Kubernetes cluster
          topologyKey: kubernetes.io/hostname

# Following Catena-X Helm Best Practices @url: https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01/
# @url: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L210
# -- Checks whether a pod is alive or not
livenessProbe:
  # -- Number of failures (threshold) for a liveness probe
  failureThreshold: 3
  # -- Delay in seconds after which an initial liveness probe is checked
  initialDelaySeconds: 250
  # -- Wait time in seconds between liveness probes
  periodSeconds: 25
  # -- Number of trys until a pod is marked alive
  successThreshold: 1
  # -- Timeout in seconds of the liveness probe
  timeoutSeconds: 1
# -- Checks if the pod is fully ready to operate
readinessProbe:
  # -- Number of failures (threshold) for a readiness probe
  failureThreshold: 3
  # -- Delay in seconds after which an initial readiness probe is checked
  initialDelaySeconds: 250
  # -- Wait time in seconds between readiness probes
  periodSeconds: 25
  # -- Number of trys until a pod is marked ready
  successThreshold: 1
  # -- Timeout in seconds of the readiness probe
  timeoutSeconds: 1

# APPLICATION SPECIFIC
puris:
    api:
      # -- The root directory of the API
      rootDir: /catena
    datasource:
      # -- Driver class name of the database
      driverClassName: org.hsqldb.jdbc.JDBCDriver
      # -- URL of the database
      url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
      # -- Username of the database
      username: sa
      # -- Password for the database user.
      # Do not set a password!
      password:
    edc:
      controlplane:
          # -- IP address of the EDC control plane
          host: 172.17.0.2
          data:
              # -- Data path of the EDC control plane
              path: /api/v1/data
              # -- Data port of the EDC control plane
              port: 30091
          # -- Key for the EDC control plane
          key: ""
      backend:
          # -- URL of the EDC backend service
          url: http://172.17.0.2:32084
      applydataplaneworkaround: true
      dataplane:
          public:
              # -- Public port of the EDC data plane
              port: 30784
      # -- Own IDS URL of the EDC
      idsUrl: http://plato-controlplane:8084/api/v1/ids
    minikube:
      # -- IP of minikube for the EDC configuration
      ip: host.minikube.internal
    own:
      # -- Own BPNL of the EDC
      bpnl: BPNL1234567890ZZ
      default:
          # -- Own default BPNA of the EDC
          bpna: BPNA1234567890AA
          # -- Own default BPNS of the EDC
          bpns: BPNS1234567890ZZ
          # -- Own default country
          country: Germany
          site:
              # -- Own site name
              name: puris-test
          # -- Own street and number
          streetnumber: "Musterstra√üe 110A"
          # -- Own zipcode and city
          zipcodeandcity: "12345 Musterhausen"
      edr:
          # -- Number of minutes before received authentication data of a consumer pull is removed from memory
          deletiontimer: 2
      # -- Own name (self-description)
      name: test
    # -- Current version of the puris API
    apiversion: 1.0.0
    demonstrator:
        # -- Current role of the PURIS demonstrator. Default value should be empty.
        # Can be set to "customer" or "supplier" to enable demonstration setup
        role:
    jpa:
      hibernate:
          # -- Initialises SQL database with Hibernate property "create" to allow Hibernate to first drop all tables and then create new ones
          ddl-auto: create
      properties:
          hibernate:
              # -- Enables "Lazy load no trans" property to fetch of each lazy entity to open a temporary session and run inside a separate transaction
              enable_lazy_load_no_trans: true
    my:
      base:
          # -- Own base URL
          url: http://localhost
    request:
      # -- Endpoint of server for request
      serverendpoint: ${my.base.url}:${server.port}/catena/product-stock/request
      # -- Asset ID for request API
      apiassetid: product-stock-request-api
    response:
      # -- Endpoint of server for response
      serverendpoint: ${my.base.url}:${server.port}/catena/product-stock/response
      # -- Asset ID for response API
      apiassetid: product-stock-response-api
    edr:
      # -- Endpoint for EDR
      endpoint: ${my.base.url}:${server.port}/catena/edrendpoint
