apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "puris-backend.fullname" . }}
  labels:
    {{- include "puris-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "puris-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "puris-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "puris-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
            - name: API_ROOTDIR
              value: "{{ .Values.puris.api.rootDir }}"
            - name: DATASOURCE_DRIVERCLASSNAME
              value: "{{ .Values.puris.datasource.driverClassName }}"
            - name: DATASOURCE_URL
              value: "{{ .Values.puris.datasource.url }}"
            - name: DATASOURCE_USERNAME
              value: "{{ .Values.puris.datasource.username }}"
            - name: DATASOURCE_PASSWORD
              value: "{{ .Values.puris.datasource.password }}"
            - name: EDC_CONTROLPLANE_HOST
              value: "{{ .Values.puris.edc.controlplane.host }}"
            - name: EDC_CONTROLPLANE_DATA_PATH
              value: "{{ .Values.puris.edc.controlplane.data.path }}"
            - name: EDC_CONTROLPLANE_DATA_PORT
              value: "{{ .Values.puris.edc.controlplane.data.port }}"
            - name: EDC_CONTROLPLANE_KEY
              value: "{{ .Values.puris.edc.controlplane.key | default (randAlphaNum 16) }}"
            - name: EDC_BACKEND_URL
              value: "{{ .Values.puris.edc.backend.url }}"
            - name: EDC_APPLYDATAPLANEWORKAROUND
              value: "{{ .Values.puris.edc.applydataplaneworkaround }}"
            - name: EDC_DATAPLANE_PUBLIC_PORT
              value: "{{ .Values.puris.edc.dataplane.public.port }}"
            - name: EDC_IDSURL
              value: "{{ .Values.puris.edc.idsurl }}"
            - name: MINIKUBE_IP
              value: "{{ .Values.puris.minikube.ip }}"
            - name: OWN_BPNA
              value: "{{ .Values.puris.own.default.bpna }}"
            - name: OWN_BPNL
              value: "{{ .Values.puris.own.bpnl }}"
            - name: OWN_BPNS
              value: "{{ .Values.puris.own.default.bpns }}"
            - name: OWN_COUNTRY
              value: "{{ .Values.puris.own.default.country }}"
            - name: OWN_EDR_DELETIONTIMER
              value: "{{ .Values.puris.own.edr.deletiontimer }}"
            - name: OWN_NAME
              value: "{{ .Values.puris.own.name }}"
            - name: OWN_SITE
              value: "{{ .Values.puris.own.default.site.name }}"
            - name: OWN_STREETNUMBER
              value: "{{ .Values.puris.own.default.streetnumber }}"
            - name: OWN_ZIPCODEANDCITY
              value: "{{ .Values.puris.own.default.zipcodeandcity }}"
            - name: PURIS_APIVERSION
              value: "{{ .Values.puris.apiversion }}"
            - name: PURIS_DEMONSTRATOR_ROLE
              value: "{{ .Values.puris.demonstrator.role }}"
            - name: JPA_HIBERNATE_DDL-AUTO
              value: {{ index .Values "puris" "jpa" "hibernate" "ddl-auto" }} #Need to do workaround because of '-' in ddl-auto
            - name: JPA_PROPERTIES_HIBERNATE_ENABLE.LAZY.LOAD.NO.TRANS
              value: "{{ .Values.puris.jpa.properties.hibernate.enable_lazy_load_no_trans }}"
            - name: MY_BASE_URL
              value: "{{ .Values.puris.my.base.url }}"
            - name: REQUEST_SERVERENDPOINT
              value: "{{ .Values.puris.request.serverendpoint }}"
            - name: REQUEST_APIASSETID
              value: "{{ .Values.puris.request.apiassetid }}"
            - name: RESPONSE_SERVERENDPOINT
              value: "{{ .Values.puris.response.serverendpoint }}"
            - name: RESPONSE_APIASSETID
              value: "{{ .Values.puris.response.apiassetid }}"
            - name: EDR_ENDPOINT
              value: "{{ .Values.puris.edr.endpoint }}"

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /catena/health/
              port: http
          readinessProbe:
            httpGet:
              path: /catena/health/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
